name: site

on:
  push:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  site:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: site
        run: |
          gem install rb-fsevent -v '0.11.0'
          bundle install
          awestruct -P production
          tar cfz _site.zip _site

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: |
            .awestruct/**
            _site.zip
          if-no-files-found: error

